// 389. Find the Difference
/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
*/
{
    var findTheDifference = function (s, t) {
        if (s.length === 0) return t[0];

        var getSumCharCode = function (str) {

            let sum = 0;
            for (let i = 0; i < str.length; i++) {
                sum = sum + str.charCodeAt(i);
            }
            return sum;
        }

        let sum1 = getSumCharCode(s);
        let sum2 = getSumCharCode(t);

        return String.fromCharCode(sum2 - sum1);
    };
}
{
    var findTheDifference = function (s, t) {
        let c = {};
        for (let i = 0; i < s.length; i += 1) {
            const char = s[i];
            if (c[char]) {
                c[char] = c[char] + 1
            } else {
                c[char] = 1;
            }
        }

        for (let i = 0; i < t.length; i += 1) {
            const char = t[i];
            if (c[char]) {
                c[char] = c[char] - 1
            } else {
                return char;
            }
        }
    };
}
